part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const splash = _Paths.splash;
  static const base = _Paths.base;
  static const home = _Paths.home;
  static const favorites = _Paths.favorites;
  static const cart = _Paths.cart;
  static const notifications = _Paths.notifications;
  static const settings = _Paths.settings;
  static const productDetails = _Paths.productDetails;
  static const onboarding = _Paths.onboarding;
  static const login = _Paths.login;
  static const fashion = _Paths.fashion;
  static const babies = _Paths.babies;
  static const sports = _Paths.sports;
  static const furniture = _Paths.furniture;
  static const electronics = _Paths.electronics;
  static const clothing = _Paths.clothing;
  static const shoes = _Paths.shoes;
  static const accessories = _Paths.accessories;
  static const bags = _Paths.bags;
  static const babiesClothing = _Paths.babiesClothing;
  static const babiesFurniture = _Paths.babiesFurniture;
  static const diapers = _Paths.diapers;
  static const football = _Paths.football;
  static const tennis = _Paths.tennis;
  static const cricket = _Paths.cricket;
  static const livingRoom = _Paths.livingRoom;
  static const bedroom = _Paths.bedroom;
  static const kitchen = _Paths.kitchen;
  static const office = _Paths.office;
  static const phones = _Paths.phones;
  static const laptops = _Paths.laptops;
  static const electronicsAccessories = _Paths.electronicsAccessories;
  static const buyNow = _Paths.buyNow;
  static const buyNowAddress = _Paths.buyNowAddress;
  static const buyNowPayment = _Paths.buyNowPayment;
  static const buyNowConfirmation = _Paths.buyNowConfirmation;
  static const buyNowSuccess = _Paths.buyNowSuccess;
  static const cars = _Paths.cars;
  static const bikes = _Paths.bikes;
  static const trucks = _Paths.trucks;
  static const parts = _Paths.parts;
}

abstract class _Paths {
  _Paths._();
  static const splash = '/splash';
  static const base = '/base';
  static const home = '/home';
  static const favorites = '/favorites';
  static const cart = '/cart';
  static const notifications = '/notifications';
  static const settings = '/settings';
  static const productDetails = '/product-details';
  static const onboarding = '/onboarding';
  static const login = '/login';
  static const fashion = '/fashion';
  static const babies = '/babies';
  static const sports = '/sports';
  static const furniture = '/furniture';
  static const electronics = '/electronics';
  // static const actionFigures = '/toys/action-figures';
  // static const buildingBlocks = '/toys/building-blocks';
  // static const dolls = '/toys/dolls';
  // static const boardGames = '/toys/board-games';
  static const clothing = '/fashion/clothing';
  static const shoes = '/fashion/shoes';
  static const accessories = '/fashion/accessories';
  static const bags = '/fashion/bags';
  static const babiesClothing = '/babies/clothing';
  static const toys = '/babies/toys';
  static const babiesFurniture = '/babies/furniture';
  static const diapers = '/babies/diapers';
  static const football = '/sports/football';
  static const tennis = '/sports/tennis';
  static const cricket = '/sports/cricket';
  static const livingRoom = '/furniture/living-room';
  static const bedroom = '/furniture/bedroom';
  static const kitchen = '/furniture/kitchen';
  static const office = '/furniture/office';
  static const phones = '/electronics/phones';
  static const laptops = '/electronics/laptops';
  static const electronicsAccessories = '/electronics/accessories';
  static const buyNow = '/buy-now';
  static const buyNowAddress = '/buy-now/address';
  static const buyNowPayment = '/buy-now/payment';
  static const buyNowConfirmation = '/buy-now/confirmation';
  static const buyNowSuccess = '/buy-now/success';
  static const cars = '/vehicle/cars';
  static const bikes = '/vehicle/bikes';
  static const trucks = '/vehicle/trucks';
  static const parts = '/vehicle/parts';
}
